name: Publish Vuepress Docs

on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 * * * *' # Every hour
    workflow_dispatch:

permissions:
    contents: write

jobs:
    publish:
        runs-on: ubuntu-latest
        env:
            GITHUB_ACCESS_TOKEN: secrets.ACCESS_TOKEN
        steps:
            -   uses: actions/checkout@v3
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
            -   uses: actions/setup-node@v2
                with:
                    node-version: 16

            -   run: composer install --no-progress
            -   run: bin/console projects:fetch
            -   run: bin/console docs:generate

            -   run: yarn install
            -   run: yarn build

            -   name: Publish
                uses: JamesIves/github-pages-deploy-action@v4
                with:
                    branch: gh-pages
                    folder: output/.vuepress/dist
