name: Publish Docs

on:
    push:
        branches:
            - master

jobs:
    publish:
        runs-on: ubuntu-latest
        env:
            GITHUB_ACCESS_TOKEN: secrets.ACCESS_TOKEN
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: bin/console projects:fetch
            -   run: bin/console dump-static-site

            -   name: Publish
                uses: eonx-com/github-pages-deploy-action@releases/v3
                with:
                    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                    BRANCH: gh-pages
                    FOLDER: output
