name: Publish Vuepress Docs

on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 * * * *' # Every hour
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        env:
            GITHUB_ACCESS_TOKEN: secrets.ACCESS_TOKEN
        steps:
            -   uses: eonx-com/actions-checkout@v2

            -   uses: eonx-com/actions-setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none

            -   run: composer install --no-progress
            -   run: bin/console projects:fetch
            -   run: bin/console docs:generate

            -   run: yarn install
            -   run: yarn build

            -   name: Publish
                uses: eonx-com/github-pages-deploy-action@releases/v3
                with:
                    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                    BRANCH: gh-pages
                    FOLDER: output/.vuepress/dist
